name: Build
on:
  push:
    branches: ["main"]
  workflow_call:
    inputs:
      production:
        type: boolean
        default: true

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.139.4"
          extended: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Install dependencies
        run: "pnpm i -P"
      - name: Set environment variables
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Build with Hugo
        env:
          HUGO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: ${{ inputs.production && 'production' || 'preview' }}
          HUGO_PAGE_URL: ${{ inputs.production && 'https://v2.galaxypedia.org' || 'https://CI_REPOSITORY_OWNER_SLUG-CI_ACTION_REF_NAME_SLUG.galaxypedia.pages.dev' }}
        run: |
          hugo --minify --baseURL "$HUGO_PAGE_URL"
      - name: Build Pagefind index
        run: pnpm pagefind
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages-build
          path: ./public
