name: Pull Request Validator
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: build
        uses: ./.github/workflows/hugo-build.yml
        with:
          production: false
      - name: Check for broken external links
        run: pnpm linkrot
