name: build
on:
  workflow_call:
    inputs:
      production:
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Install dependencies
        run: "pnpm i -P"
      - name: Build with Hugo
        env:
          HUGO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Build Pagefind index
        run: pnpm pagefind
      - name: Check for broken external links
        run: echo "THIS IS BREAKING CI PLEASES NO"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
