name: Pull Request Validator
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/hugo-build.yml
    with:
      production: false

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Check for broken external links
        run: pnpm linkrot
